# Generated by Django 4.2.5 on 2023-09-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название датчика')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура, оС')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время измерения')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurement.sensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['sensor', 'created_at'],
            },
        ),
    ]
